// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcwa0bBoINIks7JLp5eESjqKNj4AlOSm4',
    appId: '1:221389557876:web:d86d9794d9d41e40e64121',
    messagingSenderId: '221389557876',
    projectId: 'leagueit-e6a05',
    authDomain: 'leagueit-e6a05.firebaseapp.com',
    storageBucket: 'leagueit-e6a05.firebasestorage.app',
    measurementId: 'G-22VZYG6ZGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0vEv083DwvVplY_bQM4RS2763D8fAo8g',
    appId: '1:221389557876:android:6fe4bca83554f2d3e64121',
    messagingSenderId: '221389557876',
    projectId: 'leagueit-e6a05',
    storageBucket: 'leagueit-e6a05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo_cndF4b2jycJrKwF2GFsIyEIMBB7R9c',
    appId: '1:221389557876:ios:c9f7485a8d30ee14e64121',
    messagingSenderId: '221389557876',
    projectId: 'leagueit-e6a05',
    storageBucket: 'leagueit-e6a05.firebasestorage.app',
    iosBundleId: 'com.example.leagueit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo_cndF4b2jycJrKwF2GFsIyEIMBB7R9c',
    appId: '1:221389557876:ios:c9f7485a8d30ee14e64121',
    messagingSenderId: '221389557876',
    projectId: 'leagueit-e6a05',
    storageBucket: 'leagueit-e6a05.firebasestorage.app',
    iosBundleId: 'com.example.leagueit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcwa0bBoINIks7JLp5eESjqKNj4AlOSm4',
    appId: '1:221389557876:web:648555898d4505efe64121',
    messagingSenderId: '221389557876',
    projectId: 'leagueit-e6a05',
    authDomain: 'leagueit-e6a05.firebaseapp.com',
    storageBucket: 'leagueit-e6a05.firebasestorage.app',
    measurementId: 'G-1DX4V1CR0X',
  );
}
